### ISSUE TITLE
Minor resume copy changes 

### ISSUE THREAD

**Issue by NicholasLYang** [Imsiaocong/Imsiaocong.github.io#1]
"with libraries like" -> "with libraries such as"

"that can extract useful data" -> "that extract useful data"

"that can extract useful data among thousands of data" is a little repetitive. What specifically was the data? Lines of text? Transactions? You can change it to: "that can extract useful data from thousands of transactions/lines of text/etc"

"that is needed by our product team" -> "for product team"

In general you can omit "our"

"Know what it is really like being a product manager for BI (Business Intelligence) products." -> "Worked with a product manager in charge of Business Intelligence (BI) products"

**Comment by Imsiaocong** [comment]
Thank you so much Yang!!!!
